// Generated by tools/generate_recipes.py; do not edit by hand.
package dev.jam.artificecreaterecipes;

import java.util.List;

public final class WorkpieceNames {
    public static final List<String> ALL = List.of(
            "incomplete_iron_bullet_batch",
            "incomplete_copper_bullet_batch",
            "incomplete_simple_mechanical_components",
            "incomplete_mechanical_components",
            "incomplete_clockwork_components",
            "incomplete_flintlock",
            "incomplete_musket",
            "incomplete_blunderbuss",
            "incomplete_blackpowder_revolver",
            "incomplete_six_shooter",
            "incomplete_arquebus",
            "incomplete_clockwork_rifle",
            "incomplete_hair_trigger_modifier",
            "incomplete_buffer_spring_modifier",
            "incomplete_gas_vent_modifier",
            "incomplete_mechanical_accelerator_modifier",
            "incomplete_mechanical_repeater_modifier",
            "incomplete_scope_attachment_modifier",
            "incomplete_bayonet_attachment_modifier",
            "incomplete_suppressor_attachment_modifier",
            "incomplete_gun_oil_modifier",
            "incomplete_chain_shot_modifier",
            "incomplete_hook_shot_modifier"
    );
    private WorkpieceNames() {}
}
