modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/DrBiznes/artifice-create-recipes/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="DrBiznes"
credits="Built on Create by the Creators of Create and Iron's Arms 'n Artifice by iron431."
displayURL="https://modrinth.com/mod/artifice-create-recipes"
logoFile="${mod_id}.png"
description='''Replaces Iron's Arms 'n Artifice crafting recipes with Create assembly lines, mixing, and compacting. Guns, bullets, components, and modifiers are built in factories.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="irons_artifice"
type="required"
versionRange="${irons_artifice_version_range}"
ordering="AFTER"
side="BOTH"
