modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''Create manufacturing recipes for Iron's Arms 'n Artifice.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="irons_artifice"
type="required"
versionRange="${irons_artifice_version_range}"
ordering="AFTER"
side="BOTH"
